### ISSUE TITLE
Add support for other remotes

### ISSUE THREAD

**Issue by leeper** [cloudyr/ghit#15]
TODO:

 - [ ] gitlab (`install_gitlab()`)
 - [x] bitbucket (`install_bitbucket()`)
 - [ ] arbitrary git repo (`install_git()`)

**Comment by imanuelcostigan** [comment]
Would you like help on Bitbucket? I am particularly interested in Bitbucket Server

**Comment by imanuelcostigan** [comment]
Although would note that the package name is pretty closely tied to Github! I was thinking of forking this repo and providing BB support and using name bbits (s for Server)

**Comment by leeper** [comment]
I would love a PR for bitbucket!

(And yes, the name is a bit narrow but I'm sure I could generate a backronym that would make sense if additional functionality was added..."Ghit Hassle-free Installer Tool", etc.)

**Comment by imanuelcostigan** [comment]
Note from PR #22: we should refactor code to minimise duplication between BB and GH

**Comment by leeper** [comment]
@imanuelcostigan Just refactored the duplicated code (https://github.com/cloudyr/ghit/commit/de15406b4a6e03310669d5b5fbaf5fa66a5ffd1d). I'm sending to CRAN.

**Comment by leeper** [comment]
Closing this due to planned deprecation of **ghit** in favor of [**remotes**](https://cran.r-project.org/package=remotes).
