### ISSUE TITLE
missing username error message

### ISSUE THREAD

**Issue by jsta** [cloudyr/ghit#17]
If one forgets to specify a user name in `ghit::install_github()` the following error is returned:

```
>  Error in strsplit(reponame, "/")[[1]] : subscript out of bounds
```

If wonder if there could be a more informative error message by running a check that reponames are valid. I would submit a pull request but I am not sure if such a check should go in the `parse_reponame` or `install_github` functions.

**Comment by leeper** [comment]
Great idea. Thanks for the PR!
