### ISSUE TITLE
Possible OS X bug

### ISSUE THREAD

**Issue by leeper** [cloudyr/ghit#20]
Reported here: https://github.com/leeper/margins/issues/44

**Comment by leeper** [comment]
Suspect this may be the same as issue just reported that indicated dependencies were not being installed.

**Comment by vikjam** [comment]
Just thought I'd chime in with a similar problem when I try to use `install_github` using Version 0.2.12.
```{r}
> ghit::install_github("leeper/rio")
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/git2r/libs/git2r.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/git2r/libs/git2r.so, 6): Symbol not found: _SSL_CTX_ctrl
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/git2r/libs/git2r.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.3/Resources/library/git2r/libs/git2r.so
```
Session info:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6
```
Let me know if I can provide more information!

**Comment by leeper** [comment]
Can you show me the full session info, including loaded packages?

**Comment by vikjam** [comment]
Sorry, I should have included that in my report. In a fresh session, I'm no longer experiencing the issue. Thanks for the quick response nonetheless!
