### ISSUE TITLE
How to install with authentication token

### ISSUE THREAD

**Issue by filipsch** [cloudyr/ghit#21]
`ghit` is a great alternative to `devtools` if you just want to get a github package installed!

However, I'm struggling with installing a private github package using an `auth_token` that I've generated before. In `devtools::install_github`, there's the `auth_token` option for this. 

I've already dug through the source code of `git2r` to create a credentials object with an `auth_token`, but that gives me errors:

```r
> ghit::install_github("my_org/my_repo", credentials = git2r::cred_token("my_token"))
Error in git2r::fetch(gitrepo, name = "github", credentials = credentials) : 
  Error in 'git2r_remote_fetch': Unable to authenticate with supplied credentials
```

Any idea what I'm doing wrong? Thanks!

**Comment by leeper** [comment]
If you try calling fetch directly does this work?

**Comment by filipsch** [comment]
Hey, thanks for the fast response. From the `check_github()` function in your package I put together this script, but I get the same error...

``` R
> d <- tempfile(pattern = "my_package")

> dir.create(d)

> gitrepo <- git2r::init(d)

> git2r::config(gitrepo, user.name = "ghit", user.email = "example@example.com")

> git2r::remote_add(gitrepo, "github", "https://github.com/datacamp/my-package.git")

> git2r::fetch(gitrepo, name = "github", credentials = git2r::cred_token("my_token"))
Error in git2r::fetch(gitrepo, name = "github", credentials = git2r::cred_token("my_token")) : 
  Error in 'git2r_remote_fetch': Unable to authenticate with supplied credentials
```

**Comment by leeper** [comment]
Okay, I will try to investigate.

**Comment by leeper** [comment]
Closing this due to planned deprecation of **ghit** in favor of [**remotes**](https://cran.r-project.org/package=remotes).
