### ISSUE TITLE
Support gpg verified tags/commits

### ISSUE THREAD

**Issue by dirkschumacher** [cloudyr/ghit#26]
It would be cool to optionally check before installation (after `git-checkout`) if the commit or tag was signed by the correct gpg key of the package author to increase security. 

In order to support that, I think `git2r` needs to provide methods for `verify-commit` and `verify-tag` first. I therefore also created an issue at `git2r`: https://github.com/ropensci/git2r/issues/279

What do you think? I would be happy to help.

**Comment by leeper** [comment]
Good idea. I'm happy to accept a PR once git2r has the functionality.

**Comment by leeper** [comment]
Closing this due to planned deprecation of **ghit** in favor of [**remotes**](https://cran.r-project.org/package=remotes).
