### ISSUE TITLE
Using install_bitbucket_server (corporate server) on a citrix virtual machine with  no access to c:\ drive

### ISSUE THREAD

**Issue by SimonCoulombe** [cloudyr/ghit#28]
Hi!

I got everything to work, but here is what I had to do.  I am not sure what fixes could/should be done to the package, but I'll leave this here in case it is useful.

1) For some reason the system2 command wouldnt find my R program when trying to run CMD build, so I moved it from 
[64-bit]  \\svr\usr\Perso\NR\021\username\Documents\R\R-3.4.1
 to
[64-bit] Y:\R
, where Y:\ is another network drive.

2)  Change the working directory and modify base::tempdir() so that it doesnt point to a temporary folder on the  c:\\ drive.
[setwd("y:")
tempdir <- function() "y:"
unlockBinding("tempdir", baseenv())
assignInNamespace("tempdir", tempdir, ns="base", envir=baseenv())
assign("tempdir", tempdir, baseenv())
lockBinding("tempdir", baseenv())](url)

3)  Try running install_bitbucket_server.  It  downloads and builds the package, but it fails when installing:
```
library(ghit)
install_bitbucket_server( repo= "myuser/myrepo", verbose = T)
#   Installing package mypackage and 'Depends', 'Imports'
#   Error in read.dcf(file = tmpf) : cannot open the connection
#   In addition: Warning message:
#     In read.dcf(file = tmpf) :
#     cannot open compressed file 'y:/ghitdrat/bin/windows/contrib/3.4/PACKAGES', probable reason 'No such file or directory

```
4)  run utils::install.packages manually:
```
utils::install.packages("mypackage", type = "source", 
                        repos =  "file:///y:/ghitdrat",
                        verbose = T)
```
Done!   But what a ride.

**Comment by leeper** [comment]
Closing this due to planned deprecation of **ghit** in favor of [**remotes**](https://cran.r-project.org/package=remotes).
