### ISSUE TITLE
Was the CRAN submission complete?

### ISSUE THREAD

**Issue by HenrikBengtsson** [cloudyr/ghit#4]
I don't see ghit on http://cran.r-project.org/package=ghit and it's also not on ftp://cran.r-project.org/incoming/ or ftp://cran.r-project.org/incoming/save/.  Was the CRAN submission finalized?

**Comment by leeper** [comment]
Sorry, not on CRAN yet...just prepped the README for it.

**Comment by HenrikBengtsson** [comment]
I see. No worries.
